general_params:
  user: "tto"  # Username: name of the folder in the working directory
  data_directory: ""

study_params:
  study_name: ""  # Name of the study
  scanning_system: "bruker"  # Options: zeiss; 3i; bruker
  scanning_pattern: "z"  # Tilling pattern: z/s
  samples_to_process: []  # List of samples to be processed. If empty, runs on all.
  channels_to_stitch: [1, 5, 7]  # Channels to be stitched
  channels_to_segment: [5, 7]  # Channels to be segmented
  autofluorescence_channel: 1  # Autofluorescence channel
  atlas_to_use: ["mouse_gubra", "mouse_aba"]  # Options: mouse_gubra; mouse_aba; rat_waxholm.
  no_bulbs: True  # Should the reference have bulbs
  sample_permutation: [-1, 2, 3]  # Default is [1, 2, 3] = (Horizontal, Coronal, Sagittal)
  # Default is Ventral to the right, Rostral to the top, Right is high (of the image stack)

  re_process: True  # Fixme: Used to skip processing if the stitching is already done

stitching:
  search_params: [20, 20, 5]
  z_subreg_alignment: [550, 650]

cell_detection:
  save_int_results: False
  shape_detection: 150
  thresholds:
    source:
    size: [0, 500]

voxelization:
  radius: [7, 7, 7]

statistics:
  run_statistics: True
  inter_hemispherical_comparison: True

  groups:
    group_1: ["brain_1"]
    group_2: ["brain_2"]

  group_comparisons: [
  ["group_1", "group_2"],
  ]

  region_wise:
      non_parametric: True
      pval_cutoff: 1.0e-10

  voxel_wise:
      non_parametric: False
      pval_cutoff: 1.0e-10