name: cmlite
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9  # constraining seems to speed up resolution
  - cython<3
  - ipython  # autoreload functions
  - pip
  - pyyaml
  - requests
  - psutil  # required for python < 3.9 for cancelable ProcessPoolExecutors
  - natsort
  - numpy
  - pandas<2  # Groupby syntax changes
  - scipy
  - opencv
  - tifffile<2020.9.22  # Adds "Use DimensionOrder to determine axes order in OmeXml." which breaks ClearMap.IO
  - pillow
  - matplotlib
  - pyqt
  - pip:
      - scikit-image
      - h5py
      - aicsimageio
      - aicspylibczi
      - SimpleITK
      - tqdm
      - ccf-streamlines
      - pynrrd