name: cmlite
channels:
  - conda-forge
  - defaults
dependencies:
  - cython
  - matplotlib
  - numpy
  - opencv
  - pip
  - python
  - natsort
  - tifffile
  - pyyaml
  - pip:
      - aicsimageio
      - aicspylibczi
      - pandas
      - pillow
      - psutil
      - requests
      - scikit-image
      - scipy
      - tifffile